### ISSUE TITLE
连接OSStimeout咋整

### ISSUE THREAD

**Issue by SeanPC** [tencentyun/cos_migrate_tool#15]
2017-10-24 17:19:32,942 [ERROR] migrate_tool.migrator: {'status': -2, 'details': "RequestError: HTTPConnectionPool(host='kximg.oss-cn-hangzhou-internal.aliyuncs.com', port=80): Max retries exceeded with url: /?marker=&prefix=&max-keys=100&delimiter=&encoding-type=url (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6bd018dcd0>, 'Connection to kximg.oss-cn-hangzhou-internal.aliyuncs.com timed out. (connect timeout=60)'))"}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/migrate_tool/migrator.py", line 76, in work_thread
    for task in self._output_service.list():
  File "/usr/local/lib/python2.7/dist-packages/migrate_tool/services/oss.py", line 53, in list
    for obj in oss2.ObjectIterator(self._oss_api, prefix=self._prefix):
  File "/usr/local/lib/python2.7/dist-packages/oss2/iterators.py", line 43, in next
    return self.__next__()
  File "/usr/local/lib/python2.7/dist-packages/oss2/iterators.py", line 40, in __next__
    self.fetch_with_retry()
  File "/usr/local/lib/python2.7/dist-packages/oss2/iterators.py", line 48, in fetch_with_retry
    self.is_truncated, self.next_marker = self._fetch()
  File "/usr/local/lib/python2.7/dist-packages/oss2/iterators.py", line 108, in _fetch
    max_keys=self.max_keys)
  File "/usr/local/lib/python2.7/dist-packages/oss2/api.py", line 314, in list_objects
    'encoding-type': 'url'})
  File "/usr/local/lib/python2.7/dist-packages/oss2/api.py", line 1025, in __do_object
    return self._do(method, self.bucket_name, key, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oss2/api.py", line 147, in _do
    resp = self.session.do_request(req, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/oss2/http.py", line 44, in do_request
    raise RequestError(e)
RequestError: {'status': -2, 'details': "RequestError: HTTPConnectionPool(host='kximg.oss-cn-hangzhou-internal.aliyuncs.com', port=80): Max retries exceeded with url: /?marker=&prefix=&max-keys=100&delimiter=&encoding-type=url (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6bd018dcd0>, 'Connection to kximg.oss-cn-hangzhou-internal.aliyuncs.com timed out. (connect timeout=60)'))"}

**Comment by Liuchang0812** [comment]
你使用的是 oss 内网域名 kximg.oss-cn-hangzhou-internal.aliyuncs.com ，请确认网络是通的

**Comment by SeanPC** [comment]
QAQ哦哦对不住，刚刚发完就发现地址错了，，，，
然而。。。。现在，，，
报这种错。。。
![image](https://user-images.githubusercontent.com/13105794/31977352-123ba744-b96f-11e7-8e86-b004a9477b60.png)

**Comment by Liuchang0812** [comment]
去官网发工单吧

**Comment by SeanPC** [comment]
好吧
